define({
 	condition: 'location contain http at 0',
 	resource:
 	{
 		'sprite/bandit_0.png': '/little-knesset-fighter/characters/sprite/bandit_0.png',
 		'sprite/bandit_0_mirror.png': '/little-knesset-fighter/characters/sprite/bandit_0_mirror.png',
 		'sprite/bandit_1.png': '/little-knesset-fighter/characters/sprite/bandit_1.png',
 		'sprite/bandit_1_mirror.png': '/little-knesset-fighter/characters/sprite/bandit_1_mirror.png',
 		'sprite/bandit_f.png': '/little-knesset-fighter/characters/sprite/bandit_f.png',
 		'sprite/bandit_s.png': '/little-knesset-fighter/characters/sprite/bandit_s.png',
 		
 		'sprite/deep_0.png': '/little-knesset-fighter/characters/sprite/deep_0.png',
 		'sprite/deep_0_mirror.png': '/little-knesset-fighter/characters/sprite/deep_0_mirror.png',
 		'sprite/deep_1.png': '/little-knesset-fighter/characters/sprite/deep_1.png',
 		'sprite/deep_1_mirror.png': '/little-knesset-fighter/characters/sprite/deep_1_mirror.png',
 		'sprite/deep_2.png': '/little-knesset-fighter/characters/sprite/deep_2.png',
 		'sprite/deep_2_mirror.png': '/little-knesset-fighter/characters/sprite/deep_2_mirror.png',
 		'sprite/deep_ball.png': '/little-knesset-fighter/characters/sprite/deep_ball.png',
 		'sprite/deep_ball_mirror.png': '/little-knesset-fighter/characters/sprite/deep_ball_mirror.png',
 		'sprite/deep_f.png': '/little-knesset-fighter/characters/sprite/deep_f.png',
 		'sprite/deep_s.png': '/little-knesset-fighter/characters/sprite/deep_s.png',
 		
 		'sprite/davis_0.png': '/little-knesset-fighter/characters/sprite/davis_0.png',
 		'sprite/davis_1.png': '/little-knesset-fighter/characters/sprite/davis_1.png',
 		'sprite/davis_2.png': '/little-knesset-fighter/characters/sprite/davis_2.png',
 		'sprite/davis_ball.png': '/little-knesset-fighter/characters/sprite/davis_ball.png',
 		'sprite/davis_f.png': '/little-knesset-fighter/characters/sprite/davis_f.png',
 		'sprite/davis_s.png': '/little-knesset-fighter/characters/sprite/davis_s.png',
 		
 		'sprite/effect0.png': '/little-knesset-fighter/characters/sprite/effect0.png',
 		'sprite/effect0_mirror.png': '/little-knesset-fighter/characters/sprite/effect0_mirror.png',
 		'sprite/broken.png': '/little-knesset-fighter/characters/sprite/broken.png',
 		'sprite/broken2.png': '/little-knesset-fighter/characters/sprite/broken2.png',
 		
 		'sprite/weapon0.png': '/little-knesset-fighter/characters/sprite/weapon0.png',
 		'sprite/weapon0_mirror.png': '/little-knesset-fighter/characters/sprite/weapon0_mirror.png',
 		'sprite/weapon1.png': '/little-knesset-fighter/characters/sprite/weapon1.png',
 		'sprite/weapon1_mirror.png': '/little-knesset-fighter/characters/sprite/weapon1_mirror.png',
 		'sprite/weapon2.png': '/little-knesset-fighter/characters/sprite/weapon2.png',
 		'sprite/weapon2_mirror.png': '/little-knesset-fighter/characters/sprite/weapon2_mirror.png',
 		'sprite/weapon3.png': '/little-knesset-fighter/characters/sprite/weapon3.png',
 		'sprite/weapon3_mirror.png': '/little-knesset-fighter/characters/sprite/weapon3_mirror.png',
 		
 		'bg/cuhk/s.png': '/little-knesset-fighter/characters/bg/cuhk/s.png',
 		'bg/cuhk/floor1.png': '/little-knesset-fighter/characters/bg/cuhk/floor1.png',
 		'bg/cuhk/floor2.png': '/little-knesset-fighter/characters/bg/cuhk/floor2.png',
 		'bg/cuhk/floor3.png': '/little-knesset-fighter/characters/bg/cuhk/floor3.png',
 		'bg/cuhk/sky1.png': '/little-knesset-fighter/characters/bg/cuhk/sky1.png',
		'bg/cuhk/sky2.png': '/little-knesset-fighter/characters/bg/cuhk/sky2.png',
		'bg/cuhk/a1.png': '/little-knesset-fighter/characters/bg/cuhk/a1.png',
		'bg/cuhk/a2.png': '/little-knesset-fighter/characters/bg/cuhk/a2.png',
		'bg/cuhk/lib.png': '/little-knesset-fighter/characters/bg/cuhk/lib.png',
		'bg/cuhk/hill.png': '/little-knesset-fighter/characters/bg/cuhk/hill.png',
		'bg/cuhk/hill2.png': '/little-knesset-fighter/characters/bg/cuhk/hill2.png',
		'bg/cuhk/bu1.png': '/little-knesset-fighter/characters/bg/cuhk/bu1.png',
		'bg/cuhk/statue.png': '/little-knesset-fighter/characters/bg/cuhk/statue.png',
		'bg/cuhk/lamp1.png': '/little-knesset-fighter/characters/bg/cuhk/lamp1.png',
		'bg/cuhk/lamp2.png': '/little-knesset-fighter/characters/bg/cuhk/lamp2.png',
		'bg/cuhk/grass2.png': '/little-knesset-fighter/characters/bg/cuhk/grass2.png',
		'bg/cuhk/grass.png': '/little-knesset-fighter/characters/bg/cuhk/grass.png',
		'bg/cuhk/right.png': '/little-knesset-fighter/characters/bg/cuhk/right.png',
		
		'bg/ft/c1.png': '/little-knesset-fighter/characters/bg/ft/c1.png',
		'bg/ft/c2.png': '/little-knesset-fighter/characters/bg/ft/c2.png',
		'bg/ft/f1.png': '/little-knesset-fighter/characters/bg/ft/f1.png',
		'bg/ft/f2.png': '/little-knesset-fighter/characters/bg/ft/f2.png',
		'bg/ft/f3.png': '/little-knesset-fighter/characters/bg/ft/f3.png',
		'bg/ft/f4.png': '/little-knesset-fighter/characters/bg/ft/f4.png',
		'bg/ft/f5.png': '/little-knesset-fighter/characters/bg/ft/f5.png',
		'bg/ft/f6.png': '/little-knesset-fighter/characters/bg/ft/f6.png',
		'bg/ft/f7.png': '/little-knesset-fighter/characters/bg/ft/f7.png',
		'bg/ft/f8.png': '/little-knesset-fighter/characters/bg/ft/f8.png',
		'bg/ft/f9.png': '/little-knesset-fighter/characters/bg/ft/f9.png',
		'bg/ft/fa.png': '/little-knesset-fighter/characters/bg/ft/fa.png',
		'bg/ft/fb.png': '/little-knesset-fighter/characters/bg/ft/fb.png',
		'bg/ft/fc.png': '/little-knesset-fighter/characters/bg/ft/fc.png',
		'bg/ft/fd.png': '/little-knesset-fighter/characters/bg/ft/fd.png',
		'bg/ft/g1.png': '/little-knesset-fighter/characters/bg/ft/g1.png',
		'bg/ft/g2.png': '/little-knesset-fighter/characters/bg/ft/g2.png',
		'bg/ft/g3.png': '/little-knesset-fighter/characters/bg/ft/g3.png',
		'bg/ft/g4.png': '/little-knesset-fighter/characters/bg/ft/g4.png',
		'bg/ft/s.png': '/little-knesset-fighter/characters/bg/ft/s.png',
		'bg/ft/sky.png': '/little-knesset-fighter/characters/bg/ft/sky.png',
		'bg/ft/w1.png': '/little-knesset-fighter/characters/bg/ft/w1.png',
		'bg/ft/w2.png': '/little-knesset-fighter/characters/bg/ft/w2.png',
		'bg/ft/w3.png': '/little-knesset-fighter/characters/bg/ft/w3.png',
		'sprite/firen_0.png': '/little-knesset-fighter/characters/sprite/firen_0.png',
		'sprite/firen_1.png': '/little-knesset-fighter/characters/sprite/firen_1.png',
		'sprite/firen_2.png': '/little-knesset-fighter/characters/sprite/firen_2.png',
		'sprite/firen_ball.png': '/little-knesset-fighter/characters/sprite/firen_ball.png',
		'sprite/firen_exp.png': '/little-knesset-fighter/characters/sprite/firen_exp.png',
		'sprite/firen_flame.png': '/little-knesset-fighter/characters/sprite/firen_flame.png',
		'sprite/firen_f.png': '/little-knesset-fighter/characters/sprite/firen_f.png',
		'sprite/firen_grd.png': '/little-knesset-fighter/characters/sprite/firen_grd.png',
		'sprite/firen_s.png': '/little-knesset-fighter/characters/sprite/firen_s.png',
		'sprite/freeze_0.png': '/little-knesset-fighter/characters/sprite/freeze_0.png',
		'sprite/freeze_1.png': '/little-knesset-fighter/characters/sprite/freeze_1.png',
		'sprite/freeze_2.png': '/little-knesset-fighter/characters/sprite/freeze_2.png',
		'sprite/freeze_ball.png': '/little-knesset-fighter/characters/sprite/freeze_ball.png',
		'sprite/freeze_col.png': '/little-knesset-fighter/characters/sprite/freeze_col.png',
		'sprite/freeze_f.png': '/little-knesset-fighter/characters/sprite/freeze_f.png',
		'sprite/freeze_s.png': '/little-knesset-fighter/characters/sprite/freeze_s.png',
		'sprite/freeze_ww.png': '/little-knesset-fighter/characters/sprite/freeze_ww.png',
		'sprite/louis_0.png': '/little-knesset-fighter/characters/sprite/louis_0.png',
		'sprite/louis_1.png': '/little-knesset-fighter/characters/sprite/louis_1.png',
		'sprite/louis_2.png': '/little-knesset-fighter/characters/sprite/louis_2.png',
		'sprite/louis_f.png': '/little-knesset-fighter/characters/sprite/louis_f.png',
		'sprite/louis_s.png': '/little-knesset-fighter/characters/sprite/louis_s.png',
		'sprite/henry_wind.png': '/little-knesset-fighter/characters/sprite/henry_wind.png',
		'sprite/henry_arrow2.png': '/little-knesset-fighter/characters/sprite/henry_arrow2.png',
		'sprite/rudolf_smoke.png': '/little-knesset-fighter/characters/sprite/rudolf_smoke.png',
		'sprite/john_0.png': '/little-knesset-fighter/characters/sprite/john_0.png',
		'sprite/john_1.png': '/little-knesset-fighter/characters/sprite/john_1.png',
		'sprite/john_2.png': '/little-knesset-fighter/characters/sprite/john_2.png',
		'sprite/john_3.png': '/little-knesset-fighter/characters/sprite/john_3.png',
		'sprite/john_ball.png': '/little-knesset-fighter/characters/sprite/john_ball.png',
		'sprite/john_biscuit.png': '/little-knesset-fighter/characters/sprite/john_biscuit.png',
		'sprite/john_f.png': '/little-knesset-fighter/characters/sprite/john_f.png',
		'sprite/john_s.png': '/little-knesset-fighter/characters/sprite/john_s.png',
 	}
});
